[greeter]
background = /usr/share/backgrounds/navine/wallpaper.png
theme-name = Adwaita-dark
icon-theme-name = Adwaita
font-name = Sans 11
xft-antialias = true
xft-dpi = 96
xft-hintstyle = slight
xft-rgba = rgb
show-clock = true
clock-format = %a %d %b  %H:%M
indicators = ~host;~spacer;~clock;~spacer;~session;~power
user-background = false
default-user-image = #65D6FF
