"""Generate the Navine OS 8x16 kernel font from DejaVu Sans Mono.

Emits kernel/gfx/font_data.inc containing one 16-byte glyph per printable
ASCII code point (0x20..0x7E). Each byte is one scanline, bit 7 = leftmost
pixel.

DejaVu Sans Mono is distributed under the Bitstream Vera license, which
permits embedding and redistribution.

Usage: python tools/genfont.py [output.inc]
"""

import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

CELL_W = 8
CELL_H = 16
FIRST = 0x20
LAST = 0x7E
POINT_SIZE = 13

FONT_CANDIDATES = [
    "matplotlib/mpl-data/fonts/ttf/DejaVuSansMono.ttf",
    "DejaVuSansMono.ttf",
]


def find_font():
    for base in sys.path:
        for rel in FONT_CANDIDATES:
            candidate = Path(base) / rel
            if candidate.is_file():
                return candidate
    for root in Path(sys.prefix).rglob("DejaVuSansMono.ttf"):
        return root
    raise SystemExit("DejaVuSansMono.ttf not found; install matplotlib or place the font next to this script")


def render_glyph(font, codepoint):
    image = Image.new("L", (CELL_W, CELL_H), 0)
    draw = ImageDraw.Draw(image)
    ascent, _ = font.getmetrics()
    baseline = min(ascent, CELL_H - 3)
    draw.text((0, baseline), chr(codepoint), fill=255, font=font, anchor="ls")

    rows = []
    pixels = image.load()
    for y in range(CELL_H):
        bits = 0
        for x in range(CELL_W):
            if pixels[x, y] >= 112:
                bits |= 0x80 >> x
        rows.append(bits)
    return rows


def preview(codepoint, rows):
    lines = [f"  '{chr(codepoint)}' (0x{codepoint:02X})"]
    for bits in rows:
        lines.append("  " + "".join("#" if bits & (0x80 >> x) else "." for x in range(CELL_W)))
    return "\n".join(lines)


def main():
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("kernel/gfx/font_data.inc")
    font = ImageFont.truetype(str(find_font()), POINT_SIZE)

    lines = [
        "; Navine OS - 8x16 kernel font",
        "; Generated by tools/genfont.py from DejaVu Sans Mono (Bitstream Vera license).",
        "; Do not edit by hand; rerun the generator instead.",
        "",
        f"FONT_FIRST_CHAR equ 0x{FIRST:02X}",
        f"FONT_LAST_CHAR  equ 0x{LAST:02X}",
        f"FONT_CELL_W     equ {CELL_W}",
        f"FONT_CELL_H     equ {CELL_H}",
        "",
        "font_glyphs:",
    ]

    for codepoint in range(FIRST, LAST + 1):
        rows = render_glyph(font, codepoint)
        data = ",".join(f"0x{b:02X}" for b in rows)
        lines.append(f"    db {data}")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="ascii")

    glyph_count = LAST - FIRST + 1
    print(f"Wrote {out_path} ({glyph_count} glyphs, {glyph_count * CELL_H} bytes)")
    for sample in (ord("A"), ord("a"), ord("g"), ord("3")):
        print(preview(sample, render_glyph(font, sample)))


if __name__ == "__main__":
    main()
